Fix module path for editions
If the edition was missing users would get messages along the line of
```
ava.lang.IllegalAccessError: class org.enso.editions.updater.EditionUpdater (in module org.enso.editions.updater) cannot access class org.enso.downloader.http.URIBuilder (in module org.enso.downloader) because module org.enso.editions.updater does not read module org.enso.downloader
	at org.enso.editions.updater/org.enso.editions.updater.EditionUpdater.$anonfun$fetchManifests$2(EditionUpdater.scala:100)
```
which is bad.