Add locks in ExcelConnectionPool
Lack of locking was likely the reason for random test failures we
continue to experience in CI, such as
```
 INFO ide_ci::program::command: bash ℹ️ [FAILED] Read XLSX / XLS Files: [16/17, 2985ms]
 INFO ide_ci::program::command: bash ℹ️
Error: 1 did not equal 2 (at Table_Tests/src/IO/Excel_Spec.enso:1162:13-82).
 INFO ide_ci::program::command: bash ℹ️     - [FAILED] should clear cache on simulated reload [180ms]
 INFO ide_ci::program::command: bash ℹ️         Reason: 1 did not equal 2 (at Table_Tests/src/IO/Excel_Spec.enso:1162:13-82).
 INFO ide_ci::program::command: bash ℹ️
```