Inlude necessary dependencies, including java.desktop
Need to include the version of Apache Commons Compress compatible with
the `poi` version as there are some signature changes. This in turn
leads to problems with `java.desktop` as recent version of Apache
Commons deps include `module-info.java` and list `java.desktop` as
a required module.

Note: this still doesn't work as I'm getting
```
Generating big XLSX file 14:24:34.304740459
Sep 09, 2025 2:24:34 PM org.enso.interpreter.runtime.EnsoPolyglotJava createPolyglotJava
SEVERE: Using experimental OtherJvm support!
Error occurred during initialization of boot layer
java.lang.UnsatisfiedLinkError: 'int sun.nio.fs.UnixNativeDispatcher.init()'
```
when running tests.