Workaround for MacOS crash with git initialization
JGit appears to do some additional checks which,
under certain circumstances, can lead to a rather horrible crash.
This is also not necessary for our use-case so we can override the
default behaviour.

Somewhere in the initialization, JGit does for MacOS:
```bash --logic -C "which login"```
and expects a single line output. Problem occurs when bash returns more
lines. Then it crashes horribly:
```
[warn] [org.eclipse.jgit.util.FS_POSIX] Exception caught during execution of command '[bash, --login, -c, which git]' in '...', return code '141', error message '...
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

No test-case, as it would involve providing a custom bash login setup
and mocking that is certainly beyond the scope of this bug.